### ISSUE TITLE
Drive gauge rewarded to Donald, didn't effect Sora.

### ISSUE THREAD

**Issue by Snivy** [afresquet/kh2fm-randomizer#10]
Like the title says, I was playing and noticed that Donald got a drive gauge, yet it didn't affect Sora in any way. 

Attached is my pnach.
[FAF99301 - Copy.txt](https://github.com/afresquet/kh2fm-randomizer/files/4910264/FAF99301.-.Copy.txt)

**Comment by afresquet** [comment]
I've only seen this once before, and it's definitely not a randomizer/Garden of Assemblage mod problem. During a race, the player that had the CrazyCatz English patch had this issue, while the other one on Xeeynamo's didn't have a problem.

I assume due to the file name that you are playing with CC's as well. It happened repeatedly to the CC player so my only suggestion is to remake the game's ISO, since that fixed it for him. It is definitely not an issue caused by either of the mods.
