### ISSUE TITLE
Experimental Tab broken?

### ISSUE THREAD

**Issue by KoboDev** [afresquet/kh2fm-randomizer#44]
Want to get back into smashing Data Roxas face in at Timeless River.
Although I cant, is it being reworked so it can randomize ALL of the bosses?
I was thinking of visiting the discord except the readme.txt is gone.

Edit: Yes I see the changelog, but going through all of your twitter for a reason why is not good for a normal person.

**Comment by afresquet** [comment]
I dropped the project over a year ago and don't intend on coming back to it. 

The random bosses feature was causing a lot of headaches for the devs of the newer rando, since people were reporting bugs about mine that were never going to get fixed.

If you want to use random bosses/enemies consider using the newer rando.
